# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
    - pipeline: mySourcePipeline
      source: 'MihaiV(1)'
      trigger:
        branches:
        - main

steps:
- script: echo Triggered by the source pipeline '${{ mySourcePipeline.pipelineName }}'
  displayName: 'Run a one-line script'

