apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: react-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app-container
        image: mihaivalentingeorgescu/react_app
        ports:
        - containerPort: 3000


